### ISSUE TITLE
Trailing newlines

### ISSUE THREAD

**Issue by sdd** [nrempel/sleek#4]
Hi Nick! Thanks for creating Sleek - it's way, way faster than the formatter that we use at the moment, great work :-)

The only thing preventing me from switching to it at the moment is the fact that it removes the trailing newline that is usually expected at the end of the file. Most formatters like prettier, rustfmt, etc will insert an empty new line at the end of a file if one is not there.

Is this something that could be added?

**Comment by nrempel** [comment]
Hey, thanks, glad you find it useful!

Right now, sleek is a front end to the https://github.com/shssoichiro/sqlformat-rs crate which does the formatting. It may make sense to move some or all of that functionality into sleek if sqlformat-rs considers some things I want to be out of scope.

Can you create an issue at https://github.com/shssoichiro/sqlformat-rs to see if they would be open to adding this functionality?

**Comment by sdd** [comment]
After looking at https://github.com/shssoichiro/sqlformat-rs, I think it actually makes more sense to have it in here. The context in which sqlformat-rs is formatting is not necessarily a file; it may be used in a browser, or a query editor, etc, where a trailing newline does not necessarily make sense. 

I've implemented the required changes on a fork and I'll submit them as a PR.

**Comment by nrempel** [comment]
Thanks @sdd, that makes sense! Happy to merge that.

**Comment by sdd** [comment]
That should be good now, @nrempel 👍🏼

**Comment by nrempel** [comment]
Merged, thanks!

**Comment by nrempel** [comment]
v0.3.0 published on crates.io 👍🏻
